<form method="POST" action="">
    <div class="field">
        <label>Subject Pattern</label>
        <input name="subject_pattern" type="text" placeholder="E.g. password"
          value="<?= $formData['subject_pattern'] ?>">
    </div>
    <div class="field">
        <label>API Key</label>
        <input name="api_key" type="text" value="<?= $formData['api_key'] ?>">
    </div>
    <div class="field">
        <label>API Token</label>
        <input name="api_token" type="password">
    </div>
    <div class="field"><input type="submit" value="Submit"></div>
</form>

<?php if ($isFormValid) : ?>
    <b>Mail Overview:</b>
    <pre class="mail-overview"><?= $mailOverview ?></pre>

    <b>Mail Body:</b>
    <pre class="mail-body"><?= $mailBody ?></pre>
<?php endif; ?>
