<!DOCTYPE html>
<html lang="en">
    <?php
    /**
     * Layout template
     *
     * Layout/view templates are plaintext files with .phtml extension
     * containing a mix of PHP and HTML code. See $sharedViewData in
     * src/Web/WebResponse::render() on variables that are passed to templates.
     *
     * Always use external scripts instead of inline scripts:
     *   - Linting checks can be done easily on the JavaScript code using ESLint.
     *   - Less content in layout/view template files to process server-side.
     *   - Compliance to Content Security Policy (CSP) usually disallow inline stylesheets/scripts.
     *
     * Querystring params:
     *   - layout: Indicate whether to wrap HTML for view in layout template, 0=false, 1=true (default). Useful in
     *     client-side AJAX calls that populate part of a page in which the base stylesheets/scripts are already loaded.
     */
    ?>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="version" content="<?= $version ?>">
        <meta name="request-id" content="<?= $requestId ?>">
        <title>Get Mail</title>

        <link rel="icon" type="image/x-icon" href="/assets/images/favicon.png?ver=<?= $version ?>">
        <link rel="stylesheet" type="text/css" href="/assets/css/layout.css?ver=<?= $version ?>">
    </head>

    <body>
        <div class="getmail-container">
            <?= $body ?>
        </div>

        <script src="/assets/js/layout.js?ver=<?= $version ?>"></script>
    </body>
</html>
