<!DOCTYPE html>
<html lang="en">
    <?php
    /**
     * Layout template
     *
     * See $sharedViewData in src/Web/WebResponse::render() on variables that
     * are passed to layout and view templates.
     */
    ?>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="version" content="<?= $version ?>">
        <meta name="request-id" content="<?= $requestId ?>">
        <title>Get Mail</title>

        <link rel="icon" type="image/x-icon" href="/assets/images/favicon.png?ver=<?= $version ?>">
        <link rel="stylesheet" type="text/css" href="/assets/css/layout.css?ver=<?= $version ?>">
    </head>

    <body>
        <div class="getmail-container">
            <?php if ($errorMessage) : ?>
                <div class="error"><?= $errorMessage?></div>
            <?php endif; ?>

            <?= $body ?>
        </div>

        <script src="/assets/js/layout.js?ver=<?= $version ?>"></script>
    </body>
</html>
