<form method="POST" action="" class="js-mail-form" data-render-id="<?= $renderId ?>">
    <div class="error"><?= $form->getError() ?></div>

    <?php foreach ($form->getFields() as $field => $info) : ?>
        <div class="field">
            <?php if ($info['label']) : ?>
                <label><?= $info['label'] ?></label>
            <?php endif; ?>

            <input name="<?= $field ?>" type="<?= $info['type'] ?>" placeholder="<?= $info['placeholder'] ?>"
                value="<?= ($info['value'] ?? '') ?>">

            <div class="error"><?= $info['error'] ?></div>
        </div>
    <?php endforeach; ?>
</form>

<?php if ($form->isValid()) : ?>
    <hr>
    <h3>Results</h3>

    <b>Mail Overview:</b>
    <pre class="mail-overview"><?= $mailOverview ?></pre>

    <b>Mail Body (plaintext):</b>
    <pre class="mail-body"><?= $mailBody ?></pre>
<?php endif; ?>

<script src="/assets/js/mail.js?ver=<?= $version ?>"
  data-render-selector=".js-mail-form[data-render-id='<?= $renderId ?>']"></script>
